name: manage-azure-policy-1e92dc16
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Monitor/Deploy/policies/Deploy_the_Log_Analytics_in_the_subscription_Deploy-Log-Analytics/**'
#      - 'Monitor/Deploy/policies/Deploy_the_configurations_to_the_Log_Analytics_in_the_subscription_Deploy-LA-Config/**'
#      - 'Monitor/Deploy/policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**'
#      - 'Monitor/Deploy/policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**'
#      - .github/workflows/manage-azure-policy-1e92dc16.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1e92dc16}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Monitor/Deploy/policies/Deploy_the_Log_Analytics_in_the_subscription_Deploy-Log-Analytics/**
          Monitor/Deploy/policies/Deploy_the_configurations_to_the_Log_Analytics_in_the_subscription_Deploy-LA-Config/**
          Monitor/Deploy/policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**
          Monitor/Deploy/policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**
