name: manage-azure-policy-5f6195d3
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'SQL/initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**'
#      - 'SQL/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**'
#      - 'SQL/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**'
#      - 'SQL/policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**'
#      - 'SQL/policies/Public_network_access_should_be_disabled_for_PostgreSql_Deny-PublicEndpoint-PostgreSql/**'
#      - 'SQL/policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_Deny-PublicEndpoint-Sql/**'
#      - 'SQL/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**'
#      - 'SQL/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**'
#      - 'SQL/policies/Azure_Database_for_MySQL_server_deploy_a_specific_min_TLS_version_and_enforce_SSL._Deploy-MySQL-sslEnforcement/**'
#      - 'SQL/policies/Azure_Database_for_PostgreSQL_server_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL_Deploy-PostgreSQL-sslEnforcement/**'
#      - 'SQL/policies/Deploy_SQL_database_auditing_settings_Deploy-Sql-AuditingSettings/**'
#      - 'SQL/policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**'
#      - 'SQL/policies/Deploy_SQL_Database_Transparent_Data_Encryption_Deploy-Sql-Tde/**'
#      - 'SQL/policies/Deploy_SQL_Database_vulnerability_Assessments_Deploy-Sql-vulnerabilityAssessments/**'
#      - 'SQL/policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**'
#      - 'SQL/policies/Deploy_SQL_Database_security_Alert_Policies_configuration_with_email_admin_accounts_Deploy-Sql-SecurityAlertPolicies/**'
#      - .github/workflows/manage-azure-policy-5f6195d3.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5f6195d3}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          SQL/initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**
          SQL/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**
          SQL/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**
          SQL/policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**
          SQL/policies/Public_network_access_should_be_disabled_for_PostgreSql_Deny-PublicEndpoint-PostgreSql/**
          SQL/policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_Deny-PublicEndpoint-Sql/**
          SQL/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**
          SQL/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**
          SQL/policies/Azure_Database_for_MySQL_server_deploy_a_specific_min_TLS_version_and_enforce_SSL._Deploy-MySQL-sslEnforcement/**
          SQL/policies/Azure_Database_for_PostgreSQL_server_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL_Deploy-PostgreSQL-sslEnforcement/**
          SQL/policies/Deploy_SQL_database_auditing_settings_Deploy-Sql-AuditingSettings/**
          SQL/policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**
          SQL/policies/Deploy_SQL_Database_Transparent_Data_Encryption_Deploy-Sql-Tde/**
          SQL/policies/Deploy_SQL_Database_vulnerability_Assessments_Deploy-Sql-vulnerabilityAssessments/**
          SQL/policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**
          SQL/policies/Deploy_SQL_Database_security_Alert_Policies_configuration_with_email_admin_accounts_Deploy-Sql-SecurityAlertPolicies/**
